### ISSUE TITLE
Pulseaudio craches on start with SegFault error

### ISSUE THREAD

**Issue by jmtrivial** [alsa-project/alsa-plugins#31]
Dear alsa-project developers,

I am using a debian (testing) on my computer, together with deb-multimedia.org repository. As some other users with external USB audio devices, I recently discovered a segfault:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=991337
I discussed withe Christian Marillat (maintainer of the deb-multimedia repository) and we tried a couple of alsa versions, but the bug is still present if I'm using a recent libasound2-plugins such as this one:
https://www.deb-multimedia.org/tests/libasound2-plugins_1.2.2+git4219f4b-dmo1_amd64.deb
It does not crash with libasound2-plugins 1.2.2-2 from debian testing.

You will found attached the log file from pulseaudio -vvv.

[pulseaudio.log](https://github.com/alsa-project/alsa-plugins/files/6884875/pulseaudio.log)

**Comment by jmtrivial** [comment]
Dear developers,

Thanks to Christian Marillat, I give you a supplementary backtrace from gdb to identify this bug:

```
Starting program: /usr/bin/pulseaudio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
W: [pulseaudio] pid.c: Stale PID file, overwriting.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000050 in ?? ()
(gdb) bt
#0  0x0000000000000050 in ?? ()
#1  0x00007ffff299fe18 in snd_pcm_munmap () from /lib/x86_64-linux-gnu/libasound.so.2
#2  0x00007ffff298de5b in snd_pcm_close () from /lib/x86_64-linux-gnu/libasound.so.2
#3  0x00007ffff29a07e9 in ?? () from /lib/x86_64-linux-gnu/libasound.so.2
#4  0x00007ffff298de9d in snd_pcm_close () from /lib/x86_64-linux-gnu/libasound.so.2
#5  0x00007ffff2ac2eae in _snd_pcm_a52_open () from /lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_a52.so
#6  0x00007ffff298a535 in ?? () from /lib/x86_64-linux-gnu/libasound.so.2
#7  0x00007ffff298ab97 in ?? () from /lib/x86_64-linux-gnu/libasound.so.2
#8  0x00007ffff298dae5 in snd_pcm_open () from /lib/x86_64-linux-gnu/libasound.so.2
#9  0x00007ffff28f4d0f in pa_alsa_open_by_device_string () from /usr/lib/pulse-14.2/modules/libalsa-util.so
#10 0x00007ffff28f50dc in pa_alsa_open_by_template () from /usr/lib/pulse-14.2/modules/libalsa-util.so
#11 0x00007ffff28fe540 in ?? () from /usr/lib/pulse-14.2/modules/libalsa-util.so
#12 0x00007ffff290b670 in pa_alsa_profile_set_probe () from /usr/lib/pulse-14.2/modules/libalsa-util.so
#13 0x00007ffff2acbd63 in module_alsa_card_LTX_pa__init () from /usr/lib/pulse-14.2/modules/module-alsa-card.so
#14 0x00007ffff7e58279 in pa_module_load () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecore-14.2.so
#15 0x00007ffff2ad407b in ?? () from /usr/lib/pulse-14.2/modules/module-udev-detect.so
#16 0x00007ffff2ad50bb in module_udev_detect_LTX_pa__init () from /usr/lib/pulse-14.2/modules/module-udev-detect.so
#17 0x00007ffff7e58279 in pa_module_load () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecore-14.2.so
#18 0x00007ffff7e4436c in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecore-14.2.so
#19 0x00007ffff7e4c29b in pa_cli_command_execute_line_stateful () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecore-14.2.so
#20 0x00007ffff7e4ca01 in pa_cli_command_execute_file_stream () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecore-14.2.so
#21 0x000055555555b570 in main ()
```

**Comment by perexg** [comment]
I believe that the commit https://github.com/alsa-project/alsa-plugins/commit/da157e978d73f1947bb77637c324e19d003366d4 should fix this issue. Please, report back, if the problem persists.

**Comment by jmtrivial** [comment]
It works perfectly with this commit, without any segmentation fault. Thank you for this fix, and thanks to Christian Marillat for the build of the corresponding deb package!
